# Substitution variables used through the codebase
substitutions:
  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"
  bed:               "\U000F02E3"
  
  icon_font: light40
  text_font: roboto24
  button_on_color: "burnt_sienna"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "30s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Boot screen configuration
  boot_screen_delay: 60s

  # Set Night mode  at Mightnight
  screen_night_hour: '0'
  screen_night_minute: '0'

  # Set Day mode at 5:30am
  screen_day_hour: '5'
  screen_day_minute: '30'
  
  # Screen Size
  screen_height: '480px'
  screen_width: '480px'

  # Button 1 is a local relay
  button_1_name: "Local Light"
  button_1_id: local_light
  button_1_icon: $lightbulb
  button_1_device: "internal_relay_1"

  # Button 2 is a switch (some devcies show up as switches some as lights make sure you use the corresponding file)
  button_2_name: "Button 2"
  button_2_id: couch_lamp
  button_2_icon: $lightbulb
  button_2_device: "switch.athom_smart_plug_v3_50ebc0_switch"

  # Button 3 is an empty object that requires no settings. It just pushes everything down one button

  # Button 4 is dimmable light
  button_4_name: "RGB light"
  button_4_id: rgb_light
  button_4_icon: $string_lights
  button_4_device: light.athom_rgb_light_d93662_rgb_light_strip
  
  # Button 5 is scene
  button_5_name: "Bedtime"
  button_5_id: bedtime_scene
  button_5_icon: $bed
  button_5_device: scene.bed_time  

esphome:
  name: "guition-esp32-4848s040"
  friendly_name: "Guition480"
  comment: "Guition ESP32-4848S040 480px * 480px Smart Screen"
  
# Time update script - This is run once per second. Use it to update any time related labels.
script:
  - id: time_update
    then:
      - lambda: |-
          // No operation

packages:
  # Generic configuration for ESP32 screens
  core: !include modules/common/core.yaml
  wifi: !include modules/common/wifi.yaml
  colors: !include modules/common/color.yaml
  fonts: !include modules/common/fonts.yaml
  images: !include modules/common/images.yaml

  # Harware description file
  hardware: !include modules/hardware/guition-esp32-s3-4848s040.yaml

  # Base settings for LVGL libary
  time: !include modules/lvgl/base/time_sntp.yaml
  sensors: !include modules/lvgl/base/sensors_base.yaml
  base: !include modules/lvgl/base/base.yaml

  # Update button and relay state from Home Assistant
  button_1_sensor: !include { file: modules/sensors/basic_local_relay_button_state.yaml, vars: { id: 1 } }
  button_2_sensor: !include { file: modules/sensors/basic_switch_or_light_button_state.yaml, vars: { id: 2 } }
  button_4_sensor: !include { file: modules/sensors/dimmer_light_state.yaml, vars: { id: 4 } }


sensor:
  - platform: homeassistant
    id: daily_net_import
    entity_id: sensor.daily_net_import
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_imported_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_net_import).state' ]

  - platform: homeassistant
    id: daily_net_export
    entity_id: sensor.daily_net_export
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_exported_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_net_export).state' ]
                
  - platform: homeassistant
    id: daily_solar_energy_production
    entity_id: sensor.daily_solar_energy_production
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_solar_production_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_solar_energy_production).state' ]

  - platform: homeassistant
    id: daily_consumption
    entity_id: sensor.envoy_122030047695_energy_consumption_today
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_consumption_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_consumption).state' ]

  - platform: combination
    id: daily_net_sum
    type: linear
    name: "Daily net sum"
    sources:
      - source: daily_net_import
        coeffecient: 1.0
      - source: daily_net_export
        coeffecient: -1.0      
    on_value:
      then:
        - lvgl.label.update:
            id: daily_net_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_net_sum).state' ]      
        - if:
            condition:
              lambda: return (id(daily_net_sum).state < 0);
            then:
              - lvgl.widget.update:
                  id: daily_net_watts 
                  text_color: ep_blue
              - lvgl.image.update:
                  id: daily_net_watts_icon 
                  src: up_arrow                 
            else:
              - lvgl.widget.update:
                  id: daily_net_watts
                  text_color: ep_orange
              - lvgl.image.update:
                  id: daily_net_watts_icon 
                  src: down_arrow      

# -------------------------------------------------------------------------
# LVGL pages and buttons
# -------------------------------------------------------------------------
lvgl:
  theme: !include { file: modules/lvgl/base/theme.yaml }
  page_wrap: true

# Boot screen
  top_layer: !include { file: modules/lvgl/screens/boot_screen.yaml }

# Main Page
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      width: 100%
      bg_color: black
      bg_opa: cover
      pad_all: 5
      widgets: # Include all the buttons
        - button: !include { file: modules/lvgl/buttons/basic_local_relay_button.yaml, vars: { id: 1, height: $button_height_double } }
        - button: !include { file: modules/lvgl/buttons/basic_switch_button.yaml, vars: { id: 2, height: $button_height_single } }
        - button: !include { file: modules/lvgl/buttons/transparent_empty_button.yaml, vars: { id: 3, height: $button_height_single } }
        - button: !include { file: modules/lvgl/buttons/dimmer_light_button.yaml, vars: { id: 4, height: $button_height_double } }
        - button: !include { file: modules/lvgl/buttons/scene_button.yaml, vars: { id: 5, height: $button_height_single} }        
        - button:
            height: $button_height_single
            checkable: true
            id: lv_button_6
            widgets:
              - label:
                  align: bottom_left
                  id: lv_button_6_label
                  text: Enphase
            on_click:
                then:
                  lvgl.page.show: enphase

    - id: enphase
      width: 480px
      bg_color: White
      widgets:
        - obj:
            width: 480px
            height: 116px            
            pad_left: 8
            layout:
              type: grid
              grid_rows: [ fr(1), fr(1)]
              grid_columns: [ content, content, content, content, content, content, content ]              
              pad_column: 8
              pad_row: 5    
            widgets:
            # Imported from grid
                - image:
                    grid_cell_row_pos: 0
                    grid_cell_column_pos: 0
                    pad_top: 10
                    src: grid_icon
                - obj:
                    grid_cell_row_pos: 0
                    grid_cell_column_pos: 1
                    width: 90
                    height: 50
                    layout:
                        type: FLEX
                        flex_flow: ROW_WRAP
                        flex_align_cross: end
                        flex_align_track: center
                        pad_column: 3
                        pad_row: 1
                    widgets:
                      - label:
                          id: daily_imported_watts
                          text_font: ep22
                          text: 888.8
                      - label:
                          id: imported_units
                          text_font: ep14
                          text: kWh
                          pad_bottom: 2
                      - label:
                          text_font: ep14
                          text: Imported

            # Consumed
                - image:
                    grid_cell_row_pos: 0
                    grid_cell_column_pos: 2
                    pad_top: 20
                    pad_left: 6
                    pad_right: 6                 
                    src: arrow_right_gray
                - obj:
                    grid_cell_row_pos: 0
                    grid_cell_column_pos: 3
                    width: 120
                    height: 110
                    layout:
                        type: FLEX
                        flex_flow: ROW_WRAP
                        pad_column: 3
                        pad_row: 1
                        flex_align_main: center
                        flex_align_cross: end
                        flex_align_track: center
                    widgets:
                      - image:
                          pad_left: 25
                          pad_right: 25
                          pad_bottom: 4
                          src: house_icon
                      - label:
                          id: daily_consumption_watts
                          text_color: ep_orange
                          text_font: ep22
                          text: 888.8
                      - label:
                          id: consumed_unit
                          text_color: ep_orange
                          text_font: ep14
                          text: kWh
                          pad_bottom: 2

                      - label:
                          text_font: ep14
                          text: Consumed

            # Exported to Grid
                - image:
                    grid_cell_row_pos: 0
                    grid_cell_column_pos: 4
                    pad_top: 20
                    pad_left: 6
                    pad_right: 6
                    src: arrow_right_gray
                - image:
                    grid_cell_row_pos: 0
                    grid_cell_column_pos: 5
                    pad_top: 10
                    src: grid_icon
                - obj:
                    grid_cell_row_pos: 0
                    grid_cell_column_pos: 6
                    width: 90
                    height: 50
                    layout:
                        type: FLEX
                        flex_flow: ROW_WRAP
                        flex_align_cross: end
                        flex_align_track: center
                        pad_column: 3px
                        pad_row: 1px
                    widgets:
                      - label:
                          id: daily_exported_watts
                          text_font: ep22
                          text: 888.8
                      - label:
                          id: exported_unit
                          text_color: ep_orange
                          text_font: ep14
                          text: kWh
                          pad_bottom: 2
                      - label:
                          text_font: ep14
                          text: Exported

             # Produced             
                - image:
                    grid_cell_row_pos: 1
                    grid_cell_column_pos: 0
                    pad_top: 10
                    pad_bottom: 2
                    pad_right: 2
                    src: produced_icon
                - obj:
                    grid_cell_row_pos: 1
                    grid_cell_column_pos: 1
                    width: 90
                    height: 50
                    layout:
                        type: FLEX
                        flex_flow: ROW_WRAP
                        flex_align_cross: end
                        flex_align_track: center
                        pad_column: 3
                        pad_row: 1
                    widgets:
                      - label:
                          id: daily_solar_production_watts                      
                          text_font: ep22
                          text_color: ep_blue
                          text: 888.8
                      - label:
                          text_font: ep14
                          text_color: ep_blue
                          text: kWh
                          pad_bottom: 2

                      - label:
                          text_font: ep14
                          text: Produced
                - image:
                    grid_cell_row_pos: 1
                    grid_cell_column_pos: 2
                    pad_left: 6
                    pad_right: 6                
                    pad_top: 20
                    src: arrow_right_blue

                    
         # Net Imported           
                - obj:
                    grid_cell_row_pos: 1
                    grid_cell_column_pos: 4
                    bg_opa: TRANSP
                    width: 25

                - image:
                    id: daily_net_watts_icon
                    grid_cell_row_pos: 1
                    grid_cell_column_pos: 5
                    pad_top: 10
                    src: up_arrow  

                - obj:
                    grid_cell_row_pos: 1
                    grid_cell_column_pos: 6
                    width: 90
                    height: 50
                    layout:
                        type: FLEX
                        flex_flow: ROW_WRAP
                        flex_align_cross: end
                        flex_align_track: center
                        pad_column: 3
                        pad_row: 1
                    widgets:
                      - label:
                          id: daily_net_watts                      
                          text_font: ep22
                          text: 888.8
                      - label:
                          text_font: ep14
                          text: kWh
                          pad_bottom: 2
                      - label:
                          text_font: ep14
                          text: Net Imported
      on_click:
        then:
          lvgl.page.show: main_page   

#-------------------------------------------
# Graphics and Fonts
#-------------------------------------------
image:
  - file: https://esphome.io/_static/logo-text-on-light.svg
    id: boot_logo
    resize: 460x90
    type: RGB565
    use_transparency: true
    
    
  - file: assets/house.svg
    id: house_icon
    resize: 30x30
    type: RGB565
    use_transparency: true
    
  - file: assets/grid_icon.svg
    id: grid_icon
    resize: 30x30
    type: RGB565
    use_transparency: true

  - file: assets/produced_icon.svg
    id: produced_icon
    resize: 30x30
    type: RGB565
    use_transparency: true

  - file: assets/down_arrow.svg
    id: down_arrow
    resize: 30x30
    type: RGB565
    use_transparency: true

  - file: assets/up_arrow.svg
    id: up_arrow
    resize: 30x30
    type: RGB565
    use_transparency: true       

  - file: assets/arrow_right_gray.svg
    id: arrow_right_gray
    resize: 15x10
    type: RGB565
    use_transparency: true

  - file: assets/arrow_right_blue.svg
    id: arrow_right_blue
    resize: 15x10
    type: RGB565
    use_transparency: true

font:
  - file: "assets/epVisuelt-Regular.ttf"
    id: ep22
    size: 22
    bpp: 8
    
  - file: "assets/epVisuelt-Regular.ttf"
    id: ep14
    size: 14
    bpp: 8   