# Substitution variables used through the codebase
substitutions:
  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"
  bed:               "\U000F02E3"
  sunny:             "\U000F05A8"

  icon_font: light40
  text_font: roboto24
  text_color: white
  bg_color: black
  button_on_color: "ep_orange"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "30s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Boot screen configuration
  boot_screen_delay: 60s

  # Set Night mode  at Mightnight
  screen_night_hour: '0'
  screen_night_minute: '0'

  # Set Day mode at 5:30am
  screen_day_hour: '5'
  screen_day_minute: '30'

  # Screen Size
  screen_height: '480px'
  screen_width: '480px'
  
esphome:
  name: "guition-esp32-4848s040"
  friendly_name: "Guition480"
  comment: "Guition ESP32-4848S040 480px * 480px Smart Screen"

# Time update script - This is run once per second. Use it to update any time related labels.
script:
  - id: time_update
    then:
      - lambda: |-
          // No operation

packages:
  # Generic configuration for ESP32 screens
  # If you need Wi-Fi include this
  wifi: !include modules/base/wifi.yaml
  # Basic ESP 32 stuff
  base: !include modules/base/base.yaml
  # If you have a touch screen include this
  touchscreen: !include modules/base/touchscreen.yaml
  # If your touch screen has a backlight include this
  backlight: !include modules/base/backlignt.yaml
  # All the colors
  colors: !include modules/base/color.yaml
  # Fonts you need
  fonts: !include modules/base/fonts.yaml
  # Your Images
  images: !include modules/base/images.yaml
  # Some basic sensors
  sensors: !include modules/sensors/sensors_base.yaml
  # Styles + Themes
  theme_style: !include modules/base/theme_style.yaml

  # Harware description file - for your board
  hardware: !include modules/hardware/guition-esp32-s3-4848s040.yaml

  # This section will Update button and relay state from Home Assistant
  # Any button that has real time updates needs a section here

  # Button 1 - Local relay button with state updates
  # ha_name - will show up as a control in Home Assistant
  button_1_state: !include
    file: modules/sensors/local_relay_button_state.yaml
    vars:
      uid: button_1
      ha_name: Relay 1
      entity_id: internal_relay_1
  # Button 2 - Standard light button with state updates
  button_2_state: !include
    file: modules/sensors/switch_or_light_button_state.yaml
    vars:
      uid: button_2
      entity_id: "switch.athom_smart_plug_v3_50ebc0_switch"
  # Button 4 - Standard light button with state updates including dimming
  button_4_state: !include
    file: modules/sensors/dimmer_light_state.yaml
    vars:
      uid: button_4
      entity_id: light.athom_rgb_light_d93662_rgb_light_strip

# -------------------------------------------------------------------------
# LVGL pages and buttons
# -------------------------------------------------------------------------
lvgl:
# Boot screen
  top_layer: !include
    file: modules/screens/boot_screen.yaml
    vars:
      height: $screen_height
      width: $screen_width

# Main Page
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      width: 100%
      styles: page_style
      widgets:
        # Button 1 - Standard (double hight) internal relay button with state updates
        - button: !include
            file: modules/buttons/local_relay_button.yaml
            vars:
              uid: button_1
              height: $button_height_double
              text: Local Light
              icon: $lightbulb
        # Button 2 - Standard light button with state updates
        - button: !include
            file: modules/buttons/switch_button.yaml
            vars:
              uid: button_2
              height: $button_height_single
              text: Button 2
              icon: $lightbulb
              entity_id: "switch.athom_smart_plug_v3_50ebc0_switch"
        # Button 3 - Empty button moves the buttons below it down one
        - button: !include
            file: modules/buttons/transparent_empty_button.yaml
            vars:
              uid: empty_3
              height: $button_height_single
        # Button 4 - Dimming (double hight) light button with state updates
        - button: !include
            file: modules/buttons/dimmer_light_button.yaml
            vars:
              uid: button_4
              height: $button_height_double
              text: RGB light
              icon: $string_lights
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
