# Substitution variables used through the codebase
substitutions:
  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"

  icon_font: light40
  text_font: roboto12
  screen_height: '170px'
  screen_width: '320px'
  button_on_color: "burnt_sienna"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "120s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"

  # Boot screen configuration
  boot_screen_delay: 10s

  # Screen goes to sleep at Mightnight
  screen_sleep_hour: '0'
  screen_sleep_minute: '0'

  # Screen wakes up at 5:30am
  screen_wake_hour: '5'
  screen_wake_minute: '30'

esphome:
  name: solardisp
  friendly_name: Solar info display
  comment: "Solar info display 170px * 320px Smart Screen"

sensor:
  - platform: homeassistant
    id: solar_current_power_production
    entity_id: sensor.envoy_122030047695_current_power_production
    internal: true
    on_value:
      then:
        if:
            condition:
              sensor.in_range:
                id: solar_current_power_production
                below: 1
            then:
              - lvgl.label.update:
                  id: solarCPP
                  text:
                    format: "%.0f"
                    args: [ 'id(solar_current_power_production).state *= 1000' ]
              - lvgl.label.update:
                  id: solarCPP_unit
                  text: "W"
            else:
              - lvgl.label.update:
                  id: solarCPP
                  text:
                    format: "%.1f"
                    args: [ 'id(solar_current_power_production).state' ]
              - lvgl.label.update:
                  id: solarCPP_unit
                  text: "kW"

packages:
  # Generic configuration for ESP32 screens
  core: !include modules/common/core.yaml
  globals: !include modules/common/globals.yaml
  wifi: !include modules/common/wifi.yaml
  colors: !include modules/common/color.yaml
  fonts: !include modules/common/fonts.yaml
  images: !include modules/common/images.yaml

  # Harware description file
  hardware: !include modules/hardware/lilygo-tdisplays3.yaml

  # Base settings for LVGL libary
  time: !include modules/lvgl/base/time_sntp.yaml
  sensors: !include modules/lvgl/base/sensors_base.yaml
  base: !include modules/lvgl/base/base_no_touchscreen.yaml

  # Time update script
  time_update: !include modules/lvgl/base/time_update.yaml

# -------------------------------------------------------------------------
# LVGL pages and buttons
# -------------------------------------------------------------------------
lvgl:
  theme: !include { file: modules/lvgl/base/theme.yaml }
  page_wrap: true

# Boot screen
  top_layer: !include { file: modules/lvgl/screens/boot_screen_170x320.yaml, vars: { height: $screen_height, width: $screen_width  } }

# Main Page
  pages:
    - id: main_page
      widgets:
          - obj:
              align: CENTER
              width: $screen_width
              height: $screen_height
              bg_color: white
              bg_opa: COVER
              layout:
                type: GRID
                grid_columns: [FR(25), FR(45), FR(30)]
                grid_rows: [FR(25), FR(55), FR(20)]
              widgets:
                - obj:
                    grid_cell_column_pos: 0
                    grid_cell_row_pos: 0
                    grid_cell_column_span: 2
                    grid_cell_x_align: STRETCH
                    grid_cell_y_align: STRETCH
                    layout:
                        type: FLEX
                        flex_align_cross: end
                        flex_align_track: center
                        pad_column: 3
                        pad_row: 1
                    widgets:
                      - image:
                          src: grid_ok_30px
                      - label:
                          text_font: roboto18
                          text: "On Grid"
                - label:
                    id: display_time
                    grid_cell_column_pos: 2
                    grid_cell_row_pos: 0
                    grid_cell_x_align: end
                    pad_all: 2
                    text_font: roboto18
                    text: "12:00"

                - image:
                    src: produced_icon_80px
                    grid_cell_column_pos: 0
                    grid_cell_row_pos: 1
                    grid_cell_x_align: center
                    grid_cell_y_align: center
                - obj:
                    grid_cell_column_pos: 1
                    grid_cell_row_pos: 1
                    grid_cell_x_align: STRETCH
                    grid_cell_y_align: STRETCH
                    layout:
                        type: FLEX
                        flex_flow: ROW_WRAP
                        flex_align_cross: end
                        flex_align_track: center
                        pad_column: 3
                        pad_row: 1
                    widgets:
                      - label:
                          id: solarCPP
                          text_font: roboto48
                          text_color: ep_blue
                          text: 88.8
                      - label:
                          id: solarCPP_unit
                          text_font: roboto14
                          text_color: ep_blue
                          text: kW
                          pad_bottom: 6

                      - label:
                          width: 140
                          text_font: roboto14
                          text: Production
                - label:
                    text: "EMPTY"
                    grid_cell_column_pos: 2
                    grid_cell_row_pos: 1
                    grid_cell_x_align: STRETCH
                    grid_cell_y_align: STRETCH

