# Basic test to see if a screen is working
esphome:
  name: "smoke-test"

web_server:
  port: 80
  version: 3

logger:
  level: DEBUG

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  # Harware description file
  hardware: !include modules/hardware/sunton-esp32-2432s028R.yaml

lvgl: