# Substitution variables used through the codebase
substitutions:
  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"
  bed:               "\U000F02E3"

  icon_font: light40
  text_font: roboto24
  text_color: black
  button_on_color: "burnt_sienna"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "30s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Boot screen configuration
  boot_screen_delay: 60s

  # Set Night mode  at Mightnight
  screen_night_hour: '0'
  screen_night_minute: '0'

  # Set Day mode at 5:30am
  screen_day_hour: '5'
  screen_day_minute: '30'

  # Screen Size
  screen_height: '480px'
  screen_width: '480px'
  sdl_height: '480'
  sdl_width: '480'

esphome:
  name: "sdl-lvgl"
  friendly_name: "SDL test system"
  comment: "SDL test 480px * 480px Smart Screen"

host:
  mac_address: "62:23:45:AF:B3:06"

# Time update script - This is run once per second. Use it to update any time related labels.
script:
  - id: time_update
    then:
      - lambda: |-
          // No operation

packages:
  # Generic configuration for ESP32 screens
# SDL has no Wi-Fi
# wifi: !include modules/base/wifi.yaml
  # Basic ESP 32 stuff
  base: !include modules/base/base.yaml
  # If you have a touch screen include this
  touchscreen: !include modules/base/touchscreen.yaml
  # All the colors
  colors: !include modules/base/color.yaml
  # Fonts you need
  fonts: !include modules/base/fonts.yaml
  # Your Images
  images: !include modules/base/images.yaml
  # Some basic sensors
  sensors: !include modules/sensors/sensors_base-SDL.yaml
  # Styles + Themes
  theme_style: !include modules/base/theme_style.yaml  

  # Harware description file
  hardware: !include modules/hardware/SDL-lvgl.yaml

  # This section will Update button and relay state from Home Assistant
  # Any button that has real time updates needs a section here

  # Button 1 - Standard light button with state updates
  button_1_state: !include
    file: modules/sensors/switch_or_light_button_state.yaml
    vars:
      uid: button_1
      entity_id: "switch.athom_smart_plug_v3_50ebc0_switch"
  # Button 2 - Standard light button with state updates
  button_2_state: !include
    file: modules/sensors/switch_or_light_button_state.yaml
    vars:
      uid: button_2
      entity_id: "switch.athom_smart_plug_v3_50ebc0_switch"
  # Button 4 - Standard light button with state updates including dimming
  button_4_state: !include
    file: modules/sensors/dimmer_light_state.yaml
    vars:
      uid: button_4
      entity_id: light.athom_rgb_light_d93662_rgb_light_strip

# LVGL pages and buttons
lvgl:

# Boot screen
  top_layer: !include
    file: modules/screens/boot_screen.yaml
    vars:
      height: $screen_height
      width: $screen_width

# Main Page
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      width: 100%
      styles: page_style
      <<: !include
        file: modules/sections/swipe_navigation.yaml
      widgets:
        # Button 1 - Standard (double hight) light button with state updates
        - button: !include
            file: modules/buttons/switch_button.yaml
            vars:
              uid: button_1
              height: $button_height_double
              text: Button 1
              icon: $lightbulb
              entity_id: "switch.athom_smart_plug_v3_50ebc0_switch"
        # Button 2 - Standard light button with state updates
        - button: !include
            file: modules/buttons/switch_button.yaml
            vars:
              uid: button_2
              height: $button_height_single
              text: Button 2
              icon: $lightbulb
              entity_id: "switch.athom_smart_plug_v3_50ebc0_switch"
        # Button 3 - Empty button moves the buttons below it down one
        - button: !include
            file: modules/buttons/transparent_empty_button.yaml
            vars:
              uid: empty_3
              height: $button_height_single
        # Button 4 - Dimming (double hight) light button with state updates
        - button: !include
            file: modules/buttons/dimmer_light_button.yaml
            vars:
              uid: button_4
              height: $button_height_double
              text: RGB light
              icon: $string_lights
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/page_button.yaml
            vars:
              uid: button_5
              height: $button_height_single
              text: RGB red
              icon: $string_lights
              page: RGB1
              
        - button:
            height: $button_height_single
            id: button_6
            widgets:
              - label:
                  text_font: $icon_font
                  align: top_left
                  id: icon_button_6
                  text: $lightbulb
              - label:
                  align: bottom_left
                  id: label_button_6
                  text: "dark/light"
            # on_short_click:
                # then:
                  # - lvgl.style.update:
                      # id: page_style
                      # bg_color: white
                  # - lvgl.widget.redraw:

    - id: RGB1
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      width: 100%
      styles: page_style
      <<: !include
        file: modules/sections/swipe_navigation.yaml
      widgets:
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xFF0000"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xFF4500"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xFF7518"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xFFBF00"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xF4A400"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xFFC72C"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xFFC000"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xFFFF00"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0x32CD32"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0x90EE90"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0x008000"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0x93E9BE"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0x40E0D0"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0x4682B4"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0x0000FF"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0x8F00FF"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xA020F0"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xE6E6FA"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xFF69B4"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
        - button: !include
            file: modules/buttons/color_picker.yaml
            vars:
              color: "0xFF1493"
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip

