# Substitution variables used through the codebase
substitutions:
  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"

  icon_font: light40
  text_font: roboto24
  screen_height: '480px'
  screen_width: '480px'
  sdl_height: '480'
  sdl_width: '480'
  button_on_color: "burnt_sienna"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "10s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Boot screen configuration
  boot_screen_delay: 60s

  # Screen goes to sleep at Mightnight
  screen_sleep_hour: '0'
  screen_sleep_minute: '0'

  # Screen wakes up at 5:30am
  screen_wake_hour: '5'
  screen_wake_minute: '30'

esphome:
  name: weatherapp
  friendly_name: "Weather app"

host:
  mac_address: "62:23:45:AF:B3:05"

external_components:
  - source: github://pr#8005
    components: [lvgl]

packages:
  # Generic configuration for ESP32 screens
  core: !include modules/common/core.yaml
  globals: !include modules/common/globals.yaml
# SDL has no Wi-Fi
# wifi: !include modules/common/wifi.yaml
  colors: !include modules/common/color.yaml
  fonts: !include modules/common/fonts.yaml
  images: !include modules/common/images.yaml

  # Harware description file
  hardware: !include modules/hardware/SDL-lvgl.yaml

  # Base settings for LVGL libary
  time: !include modules/lvgl/base/time_homeassistant.yaml
  sensors: !include modules/lvgl/base/sensors_base-SDL.yaml
  base: !include modules/lvgl/base/base.yaml

  # Weather packages
  # Build icon set from .svg files
  weather_icons_80: !include
    file: modules/weather/weather_icons.yaml
    vars:
      size: 80
  # Display weather forcast using icon set (defined above)
  weather_forcast_80: !include
    file: modules/weather/weather_forecast.yaml
    vars:
      size: 80
  # Big icons for today weather   
  weather_icons_200: !include
    file: modules/weather/weather_icons.yaml
    vars:
      size: 200
  # Get todays weather and display it     
  weather_today_200: !include
    file: modules/weather/weather_today.yaml
    vars:
      size: 200     

# Styles for Weather forcast
.forcast_styles:
    - &forcast_obj_base
      height: SIZE_CONTENT
      width: SIZE_CONTENT
      bg_color: gray6
      radius: 3
      pad_top: 2
      pad_bottom : 2
      layout:
        type: flex
        flex_flow: COLUMN
        flex_align_cross: center
        flex_align_track: center
        pad_column: 0
        pad_row: 2

    - &forcast_label_base
      text_font: roboto24
      height: SIZE_CONTENT

    - &forcast_label_base_lo
      height: SIZE_CONTENT
      text_font: roboto20
      text_color: dodgerblue

    - &forcast_image_base
      height: SIZE_CONTENT

script:
  - id: time_update
    then:
      - lvgl.label.update:
          id: week_day
          text: !lambda 'return id(system_time).now().strftime("%A");'  # Weekday
      - lvgl.label.update:
          id: month_day
          text: !lambda |- # Month Day
            auto time = id(system_time).now();
            int day = time.day_of_month;
            char strftime_buf[64];
            snprintf(strftime_buf, sizeof(strftime_buf), "%s %d", time.strftime("%B").c_str(), day);
            return {strftime_buf};

lvgl:
  theme: !include { file: modules/lvgl/base/theme.yaml }
  page_wrap: true

 # Boot screen
  top_layer: !include { file: modules/lvgl/screens/boot_screen.yaml, vars: { height: $screen_height, width: $screen_width  } }

# Main Page
  pages:
      - id: main_page
        width: 100%
        bg_color: White
        widgets:
          - obj:
              height: SIZE_CONTENT
              width: SIZE_CONTENT
              x:  165
              y: -10
              widgets:
                - image:
                   src: unknown_200
                   id: weather_condition_icon
          - obj:
                width: 320
                height: 300
                x: +2
                pad_all: 0
                bg_opa: TRANSP
                layout:
                  pad_column: 0
                  pad_row: 0
                  type: GRID
                  grid_rows: [ content, content, content, content ]
                  grid_columns: [320 ]
                widgets:
                  - label:
                      height: SIZE_CONTENT
                      width: SIZE_CONTENT
                      text: "Wednesday"
                      id: week_day
                      text_font: roboto48
                      text_align: LEFT
                      grid_cell_row_pos: 0
                      grid_cell_column_pos: 0
                  - label:
                      text: "September 19"
                      id: month_day
                      text_font: roboto24
                      text_align: LEFT
                      grid_cell_row_pos: 1
                      grid_cell_column_pos: 0
                  - label:
                      text: "100°"
                      id: weather_temperature_today
                      text_font: roboto72
                      text_align: LEFT
                      grid_cell_row_pos: 2
                      grid_cell_column_pos: 0
                  - label:
                      width: 320
                      height: 90
                      text: "Generic weather forecast: Weather will be lovely today. Very Sunny. You will love it."
                      id: weather_condition_today
                      long_mode: wrap
                      scrollable: true
                      text_font: roboto20
                      text_align: LEFT
                      grid_cell_row_pos: 3
                      grid_cell_column_pos: 0

          - obj:
              y: +306
              width: SIZE_CONTENT
              height: SIZE_CONTENT
              layout:
                type: GRID
                grid_rows: [ content ]
                grid_columns: [ 80, 80, 80, 80 ]
                pad_column: 4
                pad_row: 0
              widgets:
                  - obj:
                      <<: *forcast_obj_base
                      grid_cell_row_pos: 0
                      grid_cell_column_pos: 0
                      widgets:
                          - label:
                              id: forecast_day_0
                              <<: *forcast_label_base
                              text: ???
                          - image:
                              id: forecast_condition_icon_0
                              <<: *forcast_label_base
                              src: unknown_80
                          - label:
                              id: forecast_temperature_hi_0
                              <<: *forcast_label_base
                              text: "---°"
                          - label:
                              id: forecast_temperature_lo_0
                              <<: *forcast_label_base_lo
                              text: "---°"
                  - obj:
                      <<: *forcast_obj_base
                      grid_cell_row_pos: 0
                      grid_cell_column_pos: 1
                      widgets:
                          - label:
                              id: forecast_day_1
                              <<: *forcast_label_base
                              text: ???
                          - image:
                              id: forecast_condition_icon_1
                              <<: *forcast_label_base
                              src: unknown_80
                          - label:
                              id: forecast_temperature_hi_1
                              <<: *forcast_label_base
                              text: "---°"
                          - label:
                              id: forecast_temperature_lo_1
                              <<: *forcast_label_base_lo
                              text: "---°"
                  - obj:
                      <<: *forcast_obj_base
                      grid_cell_row_pos: 0
                      grid_cell_column_pos: 2
                      widgets:
                          - label:
                              id: forecast_day_2
                              <<: *forcast_label_base
                              text: ???
                          - image:
                              id: forecast_condition_icon_2
                              <<: *forcast_label_base
                              src: unknown_80
                          - label:
                              id: forecast_temperature_hi_2
                              <<: *forcast_label_base
                              text: "---°"
                          - label:
                              id: forecast_temperature_lo_2
                              <<: *forcast_label_base_lo
                              text: "---°"
                  - obj:
                      <<: *forcast_obj_base
                      grid_cell_row_pos: 0
                      grid_cell_column_pos: 3
                      widgets:
                          - label:
                              id: forecast_day_3
                              <<: *forcast_label_base
                              text: ???
                          - image:
                              id: forecast_condition_icon_3
                              <<: *forcast_label_base
                              src: unknown_80
                          - label:
                              id: forecast_temperature_hi_3
                              <<: *forcast_label_base
                              text: "---°"
                          - label:
                              id: forecast_temperature_lo_3
                              <<: *forcast_label_base_lo
                              text: "---°"
