# Substitution variables used through the codebase
substitutions:
  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"

  icon_font: light40
  text_font: roboto24
  screen_height: '480px'
  screen_width: '480px'
  sdl_height: '480'
  sdl_width: '480'
  button_on_color: "burnt_sienna"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "120s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Boot screen configuration
  boot_screen_delay: 60s

  # Screen goes to sleep at Mightnight
  screen_sleep_hour: '0'
  screen_sleep_minute: '0'

  # Screen wakes up at 5:30am
  screen_wake_hour: '5'
  screen_wake_minute: '30'

esphome:
  name: weatherapp
  friendly_name: "Weather app"

host:
  mac_address: "62:23:45:AF:B3:05"

external_components:
  - source: github://pr#8005
    components: [lvgl]

packages:
  # Generic configuration for ESP32 screens
  core: !include modules/common/core.yaml
  globals: !include modules/common/globals.yaml
# SDL has no Wi-Fi
# wifi: !include modules/common/wifi.yaml
  colors: !include modules/common/color.yaml
  fonts: !include modules/common/fonts.yaml
  images: !include modules/common/images.yaml

  # Harware description file
  hardware: !include modules/hardware/SDL-lvgl.yaml

  # Base settings for LVGL libary
  time: !include modules/lvgl/base/time_homeassistant.yaml
  sensors: !include modules/lvgl/base/sensors_base-SDL.yaml
  base: !include modules/lvgl/base/base.yaml

  # Weather packages
  # Build icon set from .svg files
  weather_icons_80: !include
    file: modules/weather/weather_icons.yaml
    vars:
      size: 80
  # Display weather forcast using icon set (defined above)
  weather_forcast_80: !include
    file: modules/weather/weather_forecast.yaml
    vars:
      size: 80
  weather_icons_200: !include
    file: modules/weather/weather_icons.yaml
    vars:
      size: 200


script:
  - id: time_update
    then:
      - lvgl.label.update:
          id: week_day
          text: !lambda 'return id(system_time).now().strftime("%A");'  # weekday
      - lvgl.label.update:
          id: month_day
          text: !lambda 'return id(system_time).now().strftime("%B %-d");'  # Month Day

number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box


text_sensor:
  - platform: homeassistant
    entity_id: weather.home
    id: weather_condition
    on_value:
        then:  !include { file: modules/lvgl/weather/weather_icons_update.yaml, vars: { size: 200, id: weather_condition_icon, input_id: weather_condition  } }

  - platform: homeassistant
    entity_id: weather.home
    attribute: temperature
    id: temperature
    on_value:
        then:
          # Update weather_condition
          - lvgl.label.update:
              id: weather_temperature_today
              text:
                format: "%s°"
                args: [ 'id(temperature).state.c_str()' ]

  - platform: homeassistant
    entity_id: sensor.home_condition_day_0
    id: condition_today
    on_value:
        then:
          # Update weather_condition
          - lvgl.label.update:
              id: weather_condition_today
              text:
                format: "%s"
                args: [ 'id(condition_today).state.c_str()' ]


lvgl:
  theme: !include { file: modules/lvgl/base/theme.yaml }
  page_wrap: true

 # Boot screen
  top_layer: !include { file: modules/lvgl/screens/boot_screen.yaml, vars: { height: $screen_height, width: $screen_width  } }

  pages:
      - id: main_page
        width: 100%
        bg_color: White
        widgets:
          - obj:
                width: 400
                height: 480
                x: +2
                pad_all: 0
                layout:
                  pad_column: 0
                  pad_row: 0
                  type: GRID
                  # grid_rows: [FR(16), FR(9), FR(15), FR(18), FR(8), FR(22), FR(6), FR(6)]
                  grid_rows: [ 75px, 28px, 75px, 90px, 42px, 98px, 42px, 28px ]
                  grid_columns: [FR(25), FR(25), FR(25), FR(25)]
                widgets:
                  - label:
                      text: "Wednesday"
                      id: week_day
                      text_font: roboto72
                      text_align: LEFT
                      grid_cell_row_pos: 0
                      grid_cell_column_pos: 0
                      grid_cell_column_span: 4
                  - label:
                      text: "September 19"
                      id: month_day
                      text_font: roboto24
                      text_align: LEFT
                      grid_cell_row_pos: 1
                      grid_cell_column_pos: 0
                      grid_cell_column_span: 2
                  - label:
                      text: "100°"
                      id: weather_temperature_today
                      text_font: roboto72
                      text_align: LEFT
                      grid_cell_row_pos: 2
                      grid_cell_column_pos: 0
                      grid_cell_column_span: 2
                  - label:
                      width: 200
                      height: 90
                      text: "Generic weather forecast: Weather will be lovely today. Very Sunny. You will love it."
                      id: weather_condition_today
                      long_mode: wrap
                      scrollable: true
                      text_font: roboto20
                      text_align: LEFT
                      grid_cell_row_pos: 3
                      grid_cell_column_pos: 0
                      grid_cell_column_span: 2
                  - image:
                      src: unknown_200
                      id: weather_condition_icon
                      grid_cell_row_pos: 1
                      grid_cell_column_pos: 2
                      grid_cell_column_span: 2
                      grid_cell_row_span: 3


                  - label:
                      text: "Sat"
                      id: forecast_day_0
                      text_font: roboto36
                      grid_cell_row_pos: 4
                      grid_cell_column_pos: 0
                      grid_cell_x_align: CENTER
                  - image:
                      src: unknown_100
                      id: forecast_condition_icon_0
                      grid_cell_row_pos: 5
                      grid_cell_column_pos: 0
                      grid_cell_x_align: CENTER
                  - label:
                      text: "100°"
                      id: forecast_temperature_hi_0
                      text_font: roboto36
                      grid_cell_row_pos: 6
                      grid_cell_column_pos: 0
                      grid_cell_x_align: CENTER
                  - label:
                      text: "100°"
                      id: forecast_temperature_lo_0
                      text_font: roboto24
                      text_color: dodgerblue
                      grid_cell_row_pos: 7
                      grid_cell_column_pos: 0
                      grid_cell_x_align: CENTER

                  - label:
                      text: "Sat"
                      id: forecast_day_1
                      text_font: roboto36
                      grid_cell_row_pos: 4
                      grid_cell_column_pos: 1
                      grid_cell_x_align: CENTER
                  - image:
                      src: unknown_100
                      id: forecast_condition_icon_1
                      grid_cell_row_pos: 5
                      grid_cell_column_pos: 1
                      grid_cell_x_align: CENTER
                  - label:
                      text: "100°"
                      id: forecast_temperature_hi_1
                      text_font: roboto36
                      grid_cell_row_pos: 6
                      grid_cell_column_pos: 1
                      grid_cell_x_align: CENTER
                  - label:
                      text: "100°"
                      id: forecast_temperature_lo_1
                      text_font: roboto24
                      text_color: dodgerblue
                      grid_cell_row_pos: 7
                      grid_cell_column_pos: 1
                      grid_cell_x_align: CENTER

                  - label:
                      text: "Sat"
                      id: forecast_day_2
                      text_font: roboto36
                      grid_cell_row_pos: 4
                      grid_cell_column_pos: 2
                      grid_cell_x_align: CENTER
                  - image:
                      src: unknown_100
                      id: forecast_condition_icon_2
                      grid_cell_row_pos: 5
                      grid_cell_column_pos: 2
                      grid_cell_x_align: CENTER
                  - label:
                      text: "100°"
                      id: forecast_temperature_hi_2
                      text_font: roboto36
                      grid_cell_row_pos: 6
                      grid_cell_column_pos: 2
                      grid_cell_x_align: CENTER
                  - label:
                      text: "100°"
                      id: forecast_temperature_lo_2
                      text_font: roboto24
                      text_color: dodgerblue
                      grid_cell_row_pos: 7
                      grid_cell_column_pos: 2
                      grid_cell_x_align: CENTER

                  - label:
                      text: "Sat"
                      id: forecast_day_3
                      text_font: roboto36
                      grid_cell_row_pos: 4
                      grid_cell_column_pos: 3
                      grid_cell_x_align: CENTER
                  - image:
                      src: unknown_100
                      id: forecast_condition_icon_3
                      grid_cell_row_pos: 5
                      grid_cell_column_pos: 3
                      grid_cell_x_align: CENTER
                  - label:
                      text: "100°"
                      id: forecast_temperature_hi_3
                      text_font: roboto36
                      grid_cell_row_pos: 6
                      grid_cell_column_pos: 3
                      grid_cell_x_align: CENTER
                  - label:
                      text: "100°"
                      id: forecast_temperature_lo_3
                      text_font: roboto24
                      text_color: dodgerblue
                      grid_cell_row_pos: 7
                      grid_cell_column_pos: 3
                      grid_cell_x_align: CENTER
