esphome:
  name: "waveshare-esp32-s3-t-lcd-28c"
  friendly_name: "Waveshare-2.8-round"
  comment: "Waveshare ESP32-S3-Touch-LCD-2.8C 480px Round Screen"

# Enable logging
logger:
api:
web_server:
  port: 80
  version: 3
ota:
  platform: esphome
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  # Harware description file
  hardware: !include modules/hardware/waveshare-esp32-s3-touch-lcd-4.3.yaml

# LVGL Configuration
lvgl:
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      width: 100%
      styles: page_style
      bg_color: black
      bg_opa: cover
      <<: !include
        file: modules/sections/swipe_navigation.yaml


