esphome:
  name: "waveshare-esp32-s3-t-lcd-28c"
  friendly_name: "Waveshare-2.8-round"
  comment: "Waveshare ESP32-S3-Touch-LCD-2.8C 480px Round Screen" 

# Enable logging
logger:
api:
web_server:
  port: 80
  version: 3 
ota:
  platform: esphome
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password 

packages:  
  # Harware description file
  hardware: !include modules/hardware/waveshare-esp32-s3-touch-lcd-2.8c.yaml

# LVGL Configuration
lvgl:
  - id: lvgl_display
    displays:
      - my_display
    widgets:
      - label:
          id: coord_text
          align: CENTER
          text_align: CENTER
          text: 'Touch the screen'

touchscreen:
  - id: !extend my_touchscreen
    on_update:
        - lvgl.label.update:
            id: coord_text
            text: !lambda return str_sprintf("Touch points:\n id=%d x=%d, y=%d", touches[0].id, touches[0].x, touches[0].y);
        - lambda: |-
            for (auto touch: touches)  {
                if (touch.state <= 2) {
                  ESP_LOGI("Touch points:", "id=%d x=%d, y=%d", touch.id, touch.x, touch.y);
                }
            }
