---
# ESPHome can not send RGB arrays to Home Assistant. You need this helper.
# Include this in your configuration.yaml
#

- alias: ESPHome HueSaturation Light Set
  sequence:
    - service: light.turn_on
      data_template:
        entity_id: "{{ light_name }}"
        hs_color:
          - "{{ hue }}"
          - "{{ saturation }}"
  description: >-
    Helper to receive color light turn-on requests with the "hs_color" command
    from ESPHome devices.

- alias: ESPHome RGB Light Set
  sequence:
    - service: light.turn_on
      data_template:
        entity_id: "{{ light_name }}"
        rgb_color:
          - "{{ red }}"
          - "{{ green }}"
          - "{{ blue }}"
  description: >-
    Helper to receive color light turn-on requests with the "rgb_color" command
    from ESPHome devices.
