#You need at add energy_info.yaml to your configuration.yaml
---
sensor:
  - platform: homeassistant
    id: current_power_consumption
    entity_id: sensor.envoy_${envoy_id}_current_power_consumption
    internal: true
    on_value:
      then:
        - if:
            condition:
              lambda: 'return id(current_power_consumption).state < 9.999;'
            then:              
              - lvgl.label.update:
                  id: current_power_consumption_watts
                  text:
                    format: "%.0f"
                    args: [ '(id(current_power_consumption).state * 1000)' ]
              - lvgl.label.update:
                  id: current_power_consumption_units
                  text: W
            else:
              - lvgl.label.update:
                  id: current_power_consumption_watts
                  text:
                    format: "%.1f"
                    args: [ 'id(current_power_consumption).state' ]
              - lvgl.label.update:
                  id: current_power_consumption_units
                  text: kW                    

  - platform: homeassistant
    id: current_power_production
    entity_id: sensor.envoy_${envoy_id}_current_power_production
    internal: true
    on_value:
      then:
        - if:
            condition:
              lambda: 'return id(current_power_production).state < 9.999;'
            then:              
              - lvgl.label.update:
                  id: current_power_production_watts
                  text:
                    format: "%.0f"
                    args: [ '(id(current_power_production).state * 1000)' ]
              - lvgl.label.update:
                  id: current_power_production_units
                  text: W
            else:
              - lvgl.label.update:
                  id: current_power_production_watts
                  text:
                    format: "%.1f"
                    args: [ 'id(current_power_production).state' ]
              - lvgl.label.update:
                  id: current_power_production_units
                  text: kW   

  - platform: homeassistant
    id: daily_energy_net_import
    entity_id: sensor.daily_net_import
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_energy_imported_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_energy_net_import).state' ]

  - platform: homeassistant
    id: daily_energy_net_export
    entity_id: sensor.daily_net_export
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_energy_exported_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_energy_net_export).state' ]

  - platform: homeassistant
    id: daily_energy_production
    entity_id: sensor.daily_energy_production
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_energy_production_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_energy_production).state' ]

  - platform: homeassistant
    id: daily_energy_consumption
    entity_id: sensor.daily_energy_consumption
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_energy_consumption_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_energy_consumption).state' ]

  - platform: combination
    id: daily_energy_net_sum
    type: linear
    name: "Daily energy net sum"
    internal: true
    sources:
      - source: daily_energy_net_import
        coeffecient: 1.0
      - source: daily_energy_net_export
        coeffecient: -1.0
    on_value:
      then:
        - if:
            condition:
              lambda: return (id(daily_energy_net_sum).state < 0);
            then:
              - lvgl.widget.update:
                  id: daily_energy_net_watts
                  text_color: ep_blue
              - lvgl.image.update:
                  id: daily_energy_net_watts_icon
                  src: up_arrow
            else:
              - lvgl.widget.update:
                  id: daily_energy_net_watts
                  text_color: ep_orange
              - lvgl.image.update:
                  id: daily_energy_net_watts_icon
                  src: down_arrow
        - lvgl.label.update:
            id: daily_energy_net_watts
            text:
              format: "%.1f"
              args: [ 'fabs(id(daily_energy_net_sum).state)' ] # Always display a positive number               
                  
#-------------------------------------------
# Graphics and Fonts
#-------------------------------------------
image:
  - file: modules/assets/clock.svg
    id: clock_icon_60
    resize: 60x60
    type: RGB565
    transparency: alpha_channel
    
  - file: modules/assets/house.svg
    id: house_icon
    resize: 30x30
    type: RGB565
    transparency: alpha_channel
    
  - file: modules/assets/house.svg
    id: house_icon_60
    resize: 60x60
    type: RGB565
    transparency: alpha_channel    

  - file: modules/assets/grid_icon.svg
    id: grid_icon
    resize: 30x30
    type: RGB565
    transparency: alpha_channel

  - file: modules/assets/produced_icon.svg
    id: produced_icon
    resize: 30x30
    type: RGB565
    transparency: alpha_channel
    
  - file: modules/assets/produced_icon.svg
    id: produced_icon_60
    resize: 60x60
    type: RGB565
    transparency: alpha_channel    

  - file: modules/assets/down_arrow.svg
    id: down_arrow
    resize: 30x30
    type: RGB565
    transparency: alpha_channel

  - file: modules/assets/up_arrow.svg
    id: up_arrow
    resize: 30x30
    type: RGB565
    transparency: alpha_channel

  - file: modules/assets/arrow_right_gray.svg
    id: arrow_right_gray
    resize: 15x10
    type: RGB565
    transparency: alpha_channel

  - file: modules/assets/arrow_right_blue.svg
    id: arrow_right_blue
    resize: 15x10
    type: RGB565
    transparency: alpha_channel

font:
  - file: "modules/assets/epVisuelt-Regular.ttf"
    id: ep90
    size: 90
    bpp: 8
    
  - file: "modules/assets/epVisuelt-Regular.ttf"
    id: ep32
    size: 32
    bpp: 8

  - file: "modules/assets/epVisuelt-Regular.ttf"
    id: ep24
    size: 24
    bpp: 8 

  - file: "modules/assets/epVisuelt-Regular.ttf"
    id: ep16
    size: 16
    bpp: 8                  