#You need at add energy_info.yaml to your configuration.yaml
---
sensor:
  - platform: homeassistant
    id: current_battery_soc
    entity_id: sensor.envoy_${envoy_id}_battery
    name: "Battery SOC"
    entity_category: diagnostic
    on_value:
      then:
        - lvgl.label.update:
            id: battery_soc
            text:
              format: "%.0f%%"
              args: [ 'id(current_battery_soc).state' ]
          
binary_sensor:
  - platform: homeassistant
    id: current_grid_status
    name: "Grid status"
    entity_category: diagnostic
    entity_id: binary_sensor.enpower_${envoy_id}_grid_status
    publish_initial_state: true
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: current_grid_status
            then:
              - lvgl.label.update:
                  id: grid_status_label
                  text: "Grid Up"
              - lvgl.image.update:
                  id: grid_status_icon
                  src: grid_ok                  
            else:
              - lvgl.label.update:
                  id: grid_status_label
                  text: "Grid Down"
              - lvgl.image.update:
                  id: grid_status_icon
                  src: grid_down                  
    



#-------------------------------------------
# Graphics and Fonts
#-------------------------------------------
image:
  - file: modules/assets/battery.svg
    id: battery
    resize: 45x45
    type: RGB565
    
    transparency: alpha_channel
  - file: modules/assets/battery_100.svg
    id: battery_100
    resize: 45x45
    type: RGB565
    transparency: alpha_channel
    
  - file: modules/assets/grid_ok.svg
    id: grid_ok
    resize: 45x45
    type: RGB565
    transparency: alpha_channel

  - file: modules/assets/grid_down.svg
    id: grid_down
    resize: 45x45
    type: RGB565
    transparency: alpha_channel       
                