# sunton-esp32-2432s028
#
# Hardware configuration file

esphome:
  min_version: 2025.4.0

esp32:
  board: esp32dev
  framework:
    type: arduino

preferences:    
  flash_write_interval: 5min    

i2c:
  - sda: 27
    scl: 22

#-------------------------------------------
#  Audio output (Mono)
#-------------------------------------------
i2s_audio:
    i2s_lrclk_pin:
      number: 26
    i2s_bclk_pin:
      number: 0

speaker:
  - platform: i2s_audio
    id: speaker_id
    dac_type: external
    i2s_dout_pin: GPIO17
    sample_rate: 48000
    buffer_duration: 600ms
  - platform: mixer
    id: mixer_speaker_id
    output_speaker: speaker_id
    source_speakers:
      - id: announcement_spk_mixer_input
      - id: media_spk_mixer_input
  - platform: resampler
    id: media_spk_resampling_input
    output_speaker: media_spk_mixer_input
  - platform: resampler
    id: announcement_spk_resampling_input
    output_speaker: announcement_spk_mixer_input
    
media_player:
  - platform: speaker
    name: "Media Player"
    id: speaker_media_player_id
    media_pipeline:
        speaker: media_spk_resampling_input
        num_channels: 2
    announcement_pipeline:
        speaker: announcement_spk_resampling_input
        num_channels: 1
    
# sensor:
#   - platform: adc
#     pin: 34
#     name: "Brightness"
#     update_interval: 60s    

#-------------------------------------------
# Backlight
#-------------------------------------------
output:
  - platform: ledc
    pin: 21
    id: gpio_backlight_pwm
  - id: output_red
    platform: ledc
    pin: 4
    inverted: true
  - id: output_green
    platform: ledc
    pin: 16
    inverted: true
  - id: output_blue
    platform: ledc
    pin: 17
    inverted: true    

light:
  - platform: monochromatic # Define a monochromatic, dimmable light for the backlight
    output: gpio_backlight_pwm
    name: Display Backlight
    id: display_backlight
    restore_mode: ALWAYS_ON
  - platform: rgb
    id: rgb_led
    name: RGB LED
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF    

spi:
  - id: tft
    clk_pin: 14
    mosi_pin: 13
    miso_pin:
      number: 12
      ignore_strapping_warning: true
  - id: touch
    clk_pin: 25
    mosi_pin: 32
    miso_pin: 39

touchscreen:
  - id: my_touchscreen
    platform: xpt2046
    spi_id: touch
    cs_pin: 33
    interrupt_pin: 36
    threshold: 400
    calibration:
      x_min: 280
      x_max: 3860
      y_min: 340
      y_max: 3860
    transform:        
      mirror_x: false  # original used to be true
      mirror_y: true  #added this line
      swap_xy: false  #added this line
    # on_touch:
    #   - lambda: |-
    #         ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
    #           touch.x,
    #           touch.y,
    #           touch.x_raw,
    #           touch.y_raw
    #         );

display:
  - id: main_display
    platform: ili9xxx
    model:  TFT 2.4R    # original used to be LI9341
    spi_id: tft
    cs_pin:
      number: 15
      ignore_strapping_warning: true
    dc_pin:
      number:  2
      ignore_strapping_warning: true
    invert_colors: true   # original used to be false
    color_palette: 8BIT   # added this line
    update_interval: never
    auto_clear_enabled: false
    transform:            # added this line
      swap_xy: true
      mirror_x: false
    dimensions:           #added this line
      height: 320
      width: 240

lvgl:
  buffer_size: 25%