

esphome:
  name: waveshare-esp32-s3-touch-4
  friendly_name: waveshare-esp32-s3-touch-4
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    # board_upload.flash_size: "8MB"
    board_upload.maximum_ram_size: 524288
    board_upload.maximum_size: 8388608
  on_boot:
    then:
      - delay: 5s
      - lvgl.widget.hide: boot_screen

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_IDF_TARGET: "esp32s3"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_ESPTOOLPY_FLASHFREQ_80M: y
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_IDF_EXPERIMENTAL_FEATURES: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM: y
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_SPIRAM_SPEED_80M: y
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      COMPILER_OPTIMIZATION_SIZE: y
# Enable Home Assistant API

# captive_portal:
psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: INFO

i2c:
  - id: bus_a
    sda: GPIO08
    scl: GPIO09
    scan: True
  - id: bus_b
    sda: GPIO15
    scl: GPIO07
    scan: True
tca9555:
  id: io_ex
  i2c_id: bus_a

# Toggles backlight of Waveshare ESP32-S3-Touch-LCD-4.3
switch:
  - platform: gpio
    name: "Backlight Toggle"
    pin: 
      tca9555: io_ex
      number: 2
      mode:
        output: true
      inverted: False
    restore_mode: ALWAYS_ON

display:
  - platform: mipi_rgb
    model: WAVESHARE-4-480x480
    id: my_display

touchscreen:
  platform: gt911
  id: my_touchscreen
  display: my_display
  i2c_id: bus_b
  interrupt_pin: GPI16
  reset_pin:
    tca9555: io_ex
    number: 0
    mode: output
  on_touch:
    - lambda: |-
          ESP_LOGD("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );
  on_release:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.widget.redraw:
            # - light.turn_on: display_backlight