---
# Updates the tide clock

# -------------------------------------------
# Graphics and Fonts
# -------------------------------------------
image:
  - file: assets/tide_pointer.svg
    id: tide_pointer
    resize: 200x88 # 2.272  - 22x22
    type: RGB565
    use_transparency: true

font:
  - file: "gfonts://Roboto@700"
    id: roboto30_bold
    size: 30
    bpp: 8    
    
    
sensor:
  - platform: homeassistant
    entity_id: sensor.tides
    attribute: tide_percentage
    id: tide_percentage
    on_value:
      then:
        - lvgl.indicator.update:
            id: tide_level
            value: !lambda "return id(tide_percentage).state;"

text_sensor:
  - platform: homeassistant
    entity_id: sensor.tides
    attribute: next_tide_type
    id: next_tide_type

  - platform: homeassistant
    entity_id: sensor.tides
    attribute: next_tide_time
    id: next_tide_time
    on_value:
      - if:
          condition:
            text_sensor.state:
              id: next_tide_type
              state: 'Low'
          then:
            - lvgl.label.update:
                id: low_tide_label
                text:
                   format: "%s"
                   args: [ 'id(next_tide_time).state.c_str()' ]
          else:
            - lvgl.label.update:
                id: high_tide_label
                text:
                   format: "%s"
                   args: [ 'id(next_tide_time).state.c_str()' ]

  - platform: homeassistant
    entity_id: sensor.tides
    attribute: last_tide_type
    id: last_tide_type

  - platform: homeassistant
    entity_id: sensor.tides
    attribute: last_tide_time
    id: last_tide_time
    on_value:
      - if:
          condition:
            text_sensor.state:
              id: last_tide_type
              state: 'Low'
          then:
            - lvgl.label.update:
                id: low_tide_label
                text:
                   format: "%s"
                   args: [ 'id(last_tide_time).state.c_str()' ]
          else:
            - lvgl.label.update:
                id: high_tide_label
                text:
                   format: "%s"
                   args: [ 'id(last_tide_time).state.c_str()' ]